Actions partial
Teamasaurus/devdays pull request #41
Opened 2022-09-08 13:09 UTC by scamelot

actions out to a partial

listPosts enforces userID match

css adjustments to fix overlap / leaking out of frame on smaller screen sizes

2022-09-09 03:32 UTC, StevDev88 commented on views/partials/actions.ejs
> +        <form action="/blogPost/edit/<%= blogPost._id %>" action="GET">
Second `action` should be a `method`.

2022-09-09 04:05 UTC, StevDev88 requested changes
Switch `action` to `method` in actions.ejs partial.  Otherwise, looks good!

2022-09-09 13:17 UTC, scamelot reviewed
fixed

2022-09-09 13:17 UTC, scamelot commented on views/partials/actions.ejs
> +        <form action="/blogPost/edit/<%= blogPost._id %>" action="GET">
Change to method="GET"

2022-09-09 13:26 UTC, scamelot commented on views/partials/actions.ejs
> +        <form action="/blogPost/edit/<%= blogPost._id %>" action="GET">
fixed

2022-09-10 03:35 UTC, StevDev88 approved these changes

2022-09-10 19:16 UTC, merged